/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.edu.uttt.view;

import mx.edu.uttt.generic.SingletonLogin;

/**
 * 
 *
 * @author BONI
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        FrmMenuLogin = new javax.swing.JMenu();
        frmItemMenuLogin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        getContentPane().setLayout(null);

        jMenu1.setText("File");

        FrmMenuLogin.setText("Login");
        FrmMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrmMenuLoginActionPerformed(evt);
            }
        });

        frmItemMenuLogin.setText("Acceso");
        frmItemMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmItemMenuLoginActionPerformed(evt);
            }
        });
        FrmMenuLogin.add(frmItemMenuLogin);

        jMenu1.add(FrmMenuLogin);

        MenuPrincipal.add(jMenu1);

        jMenu2.setText("Edit");
        MenuPrincipal.add(jMenu2);

        setJMenuBar(MenuPrincipal);

        setBounds(0, 0, 779, 414);
    }// </editor-fold>//GEN-END:initComponents

    private void FrmMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmMenuLoginActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FrmMenuLoginActionPerformed

    private void frmItemMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmItemMenuLoginActionPerformed
        // TODO add your handling code here:
        //vamos a crear el singleton
        //AQUI ESTAMOS CREANDO EL SINGLETON
        SingletonLogin.getInstance().setVisible(true);
       
    }//GEN-LAST:event_frmItemMenuLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FrmMenuLogin;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenuItem frmItemMenuLogin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
